### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ezek1el** [bexem/PlexCache#16]
I installed plexapi and requests via pip and start the script with `python plexcache_setup.py` and immediately get the following error message: 
```
File "plexcache_setup.py", line 24
    raise FileNotFoundError(f'Wrong path given, please edit the "{folder}" variable accordingly.')
```
Where do i find the {folder} variable?

**Comment by ezek1el** [comment]
nevermind. Python 2 and 3 are installed. Using `python3 plexcache_setup.py` fixed the issue

**Comment by bexem** [comment]
I'm glad you fixed it, I'll leave this open for a couple of hours in case you have any other issues. ☺️

**Comment by ezek1el** [comment]
Ok, next issue i ran into:

i completed the setup without any problems. Then run the script from console with `python3 plexcache.py` and get this error:

```
*** PlexCache ***
Error: 'watched_cache_expiry' not found in settings file, please re-run the setup or manually edit the settings file.

```

I reran the setup twice. Same error. Whats going on?

**Comment by bexem** [comment]
I think it never merged a line in the setup_script, instead of rerunning everything, just add this to the settings.json
`"watched_cache_expiry": 48,` 
* Without the comma you are adding it at the end of the list.

Apologies for this, it've already fixed it, just need to merge. 
I guess I need to be more methodical in my testing.

**Comment by ezek1el** [comment]
And now it is working flawlessly. Thank you!
